### ISSUE TITLE
AttributeError: document_relateditems

### ISSUE THREAD

**Issue by mitakas** [RedTurtle/Products.FaqAttachment#1]
There is a problem with the document_relateditems macro and Plone 4.3. The related items are displayed with a viewlet below the content sind Plone 3, so it should be safe to remove the macro.

It is in this file: [browser/faqentry_view.pt: Lines 49-51](https://github.com/RedTurtle/Products.FaqAttachment/blob/0.1/Products/FaqAttachment/browser/faqentry_view.pt#L49..L51)

**Comment by keul** [comment]
@mitakas you are right, we never used hits on Plone 4+.

I fear I have no time to look into this.
Can you provide a pull request with the change?
